modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="er"
version="1.0.21"
displayName="er"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="wither123, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.er]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.er]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
# End of user code block dependencies configuration
