// Save this class in your mod and generate all required imports

/**
 * Made with Blockbench 4.12.5 Exported for Minecraft version 1.19 or later with
 * Mojang mappings
 * 
 * @author Author
 */
public class travelerAnimation {
	public static final AnimationDefinition NormalAttack1 = AnimationDefinition.Builder.withLength(1.4F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -25.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-131.0869F, -42.7599F, 74.8076F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-30.9673F, -17.143F, 54.4369F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-20.9673F, -17.143F, 54.4369F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -3.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -3.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-24.9164F, -2.1109F, -4.5336F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-22.9098F, 10.2886F, 22.9098F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-22.9098F, 10.2886F, 22.9098F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -25.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -1.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -1.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -25.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(30.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(30.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(90.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(90.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition NormalAttack2 = AnimationDefinition.Builder.withLength(1.4F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-15.0F, -45.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-15.0F, -22.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(10.0F, -75.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(10.0F, -50.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-29.6165F, 12.2931F, 40.2901F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-167.8121F, -21.7345F, 72.5945F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-148.8282F, -26.6764F, 66.0302F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -3.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(5.0F, -3.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -3.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-22.9098F, 10.2886F, 22.9098F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(23.8572F, -58.1336F, -39.9388F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(12.7726F, -15.0178F, -22.7148F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-4.0F, -2.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(-1.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-37.2495F, -44.8555F, 30.9318F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-25.6755F, -7.9781F, 6.5432F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -1.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-1.0F, -1.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(-1.0F, -1.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(30.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(36.5236F, -32.6387F, -24.66F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(30.0818F, -0.9128F, -3.4152F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -1.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-3.0F, -1.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(-2.0F, -1.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(90.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.05F, KeyframeAnimations.degreeVec(90.0F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(55.0F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(42.5F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition NormalAttack3 = AnimationDefinition.Builder.withLength(1.1F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-15.0F, -45.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -85.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, -232.0411F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(0.0F, -350.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(1.0F, -3.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -3.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(10.0F, -75.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -122.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, -180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(0.0F, -322.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(22.5F, -390.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(22.5F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -2.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(1.0F, -2.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-167.8121F, -21.7345F, 72.5945F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(-352.825F, -69.233F, 220.8936F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-300.0F, 29.5778F, 230.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-266.0058F, 45.1347F, 280.4269F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(-41.0467F, 34.1785F, 272.5713F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-46.0467F, 34.1785F, 272.5713F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(5.0F, -3.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(8.0F, -0.84F, -5.79F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(2.0F, -3.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -3.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(23.8572F, -58.1336F, -39.9388F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -90.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, -180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(0.0F, -307.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(47.5F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(-4.0F, -2.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(-7.0F, -1.0F, 4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(-1.0F, 0.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, -3.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -3.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-25.0F, -32.5F, 20.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(-195.0F, -87.5F, 180.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-157.5F, -27.5F, 160.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-150.0F, 140.0F, 190.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(-150.0F, 140.0F, 190.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-150.0F, 180.0F, 190.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(-1.0F, -1.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(3.0F, -1.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(4.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(1.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(-1.0F, -2.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, -2.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(36.5236F, -32.6387F, -24.66F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -90.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, -180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-10.0F, -300.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(-20.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-20.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(-3.0F, -1.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(-3.0F, -1.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-4.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, 0.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(55.0F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.05F, KeyframeAnimations.degreeVec(55.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(125.92F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(100.92F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.1F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition NormalAttack4 = AnimationDefinition.Builder.withLength(1.4F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -385.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -397.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(0.0F, -360.83F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(1.0F, -3.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(2.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(22.5F, -30.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(22.5F, -60.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(26.2204F, 41.4008F, 6.3396F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(22.5F, 30.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(1.0F, -2.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(2.0F, -1.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, -3.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -3.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-41.0467F, 34.1785F, 272.5713F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(56.4533F, 15.0F, 320.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-201.0467F, 15.0F, 280.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-176.0467F, 15.0F, 280.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 360.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(2.0F, -3.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(8.0F, -3.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(1.11F, -1.67F, 2.78F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(1.11F, -1.67F, 0.78F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(47.5F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(47.5F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-7.7778F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-7.7778F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, -360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -3.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(-2.0F, -3.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(0.22F, -2.67F, -3.33F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.22F, -2.67F, -2.33F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 8.3965F, 30.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -90.0F, 30.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(27.5F, 0.0F, 30.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(27.5F, 0.0F, 30.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(-1.0F, -2.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(-1.0F, 0.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(2.0F, -2.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(2.0F, -2.0F, 4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -90.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(-2.0F, 0.0F, 2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(2.0F, -1.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(3.0F, -1.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(125.92F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(250.92F, 0.0F, -180.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(283.04F, 0.0F, -160.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(283.04F, 0.0F, -160.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition NormalAttack5 = AnimationDefinition.Builder.withLength(1.8F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -360.83F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, -225.83F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(0.0F, 21.67F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(0.0F, 21.67F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 21.67F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -3.0F, 2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(-2.0F, -4.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(26.2204F, 41.4008F, 6.3396F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(15.0F, 260.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(15.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(15.0F, 400.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(25.0F, 410.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -3.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -3.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(-3.0F, -4.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(160.0F, 15.0F, 280.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(60.0F, 15.0F, 280.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-60.0F, 15.0F, 240.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-185.0F, 15.0F, 240.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-227.5F, 15.0F, 240.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(-227.5F, 15.0F, 240.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 360.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(1.11F, -1.67F, 2.78F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(9.11F, -1.67F, 2.78F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(5.11F, -1.67F, -5.22F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(-1.17F, -2.58F, 0.07F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(1.0F, -2.0F, 4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(-2.0F, -3.0F, 4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(-20.0F, 90.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-20.0F, 250.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-20.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(-20.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.22F, -2.67F, -3.33F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(-9.78F, -2.67F, -2.33F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-5.78F, -2.67F, 7.67F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.22F, -3.67F, -0.33F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(-4.78F, -3.67F, -4.33F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(27.5F, 0.0F, 30.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(35.0F, 120.0F, -15.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(10.0F, 280.0F, 25.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(27.5F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(27.5F, 390.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(40.0F, 400.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(2.0F, -2.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(5.0F, -2.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-1.0F, -2.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -2.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(1.0F, -1.88F, 2.82F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(1.0F, -1.88F, 4.82F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(15.0F, 100.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, 270.0F, -10.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-5.0F, 360.0F, -10.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-5.0F, 390.0F, -10.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(-10.0F, 390.0F, -20.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(2.0F, -1.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(-2.0F, -1.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-5.0F, -1.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -1.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(-2.0F, -1.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(125.92F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(85.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(72.5F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(72.5F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition ChargedAttack = AnimationDefinition.Builder.withLength(1.4F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, -17.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 7.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, 17.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, -45.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.degreeVec(0.0F, 30.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(84.1552F, 11.0686F, 126.9332F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.degreeVec(-157.649F, 6.5603F, 90.2804F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.35F, KeyframeAnimations.degreeVec(-169.4575F, 20.8376F, 43.4268F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(-165.4346F, 7.5053F, 87.9483F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(34.3583F, 7.7564F, 67.7693F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(1.0F, -1.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(1.0F, -1.0F, 2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.degreeVec(25.0F, -30.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.35F, KeyframeAnimations.degreeVec(80.0F, -30.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(51.2294F, 9.5083F, -6.4983F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(-44.3108F, 26.0647F, 24.2318F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.35F, KeyframeAnimations.degreeVec(0.0F, -10.0F, -25.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-33.766F, 2.4107F, -6.1533F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -3.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(-1.0F, 0.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(-1.0F, -1.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(30.9347F, 4.4598F, 21.0592F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, -32.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 12.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.5F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(0.5F, 0.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(-8.1559F, 14.6594F, -2.5621F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, -30.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 10.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.degreeVec(0.0F, 5.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -1.0F, -1.5F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition ElementalSkillAnemoStart = AnimationDefinition.Builder.withLength(0.25F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.15F, KeyframeAnimations.degreeVec(15.0F, 20.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 10.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.degreeVec(-90.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(-2.0F, -3.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.degreeVec(47.5F, 0.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, -2.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.degreeVec(-22.5F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, -1.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_item",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition ElementalSkillAnemoEnd = AnimationDefinition.Builder.withLength(0.7F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(0.0F, -17.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(0.0F, -27.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(15.0F, 20.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(15.0F, -55.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(15.0F, -65.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -2.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -2.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 10.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-27.5F, 0.0F, -25.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-27.5F, 0.0F, -25.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(1.0F, -2.0F, -6.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(1.0F, -1.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-90.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-90.0F, -30.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-90.0F, -32.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(-2.0F, -3.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-1.0F, -3.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(-2.0F, -3.0F, 2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(47.5F, 0.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(47.5F, -15.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(47.5F, -15.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -2.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-2.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(-3.0F, -2.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-22.5F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-22.5F, -15.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-22.5F, -15.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -1.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -1.0F, 2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(-2.0F, -1.0F, 2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_item",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.45F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_item",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0.3F, KeyframeAnimations.scaleVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.45F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition ElementalBurstAnemo = AnimationDefinition.Builder.withLength(0.9F)
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-75.0F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-180.0F, 270.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-180.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-290.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-390.0F, 630.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(-290.0F, 900.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.degreeVec(-290.0F, 900.0F, -45.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.degreeVec(-290.0F, 900.0F, -45.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.degreeVec(-360.0F, 1808.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -4.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -5.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -15.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, -15.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(-6.0F, -9.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(-1.0F, -8.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(1.0F, -9.0F, 6.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.posVec(2.0F, -5.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.posVec(2.0F, -5.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(17.5F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-75.0F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-180.0F, 270.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-180.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-290.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-390.0F, 630.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(-290.0F, 900.0F, 45.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.degreeVec(-290.0F, 900.0F, -35.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.degreeVec(-280.0F, 900.0F, -90.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.degreeVec(-280.0F, 900.0F, -90.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.degreeVec(-360.0F, 1080.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -4.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, -5.0F, -8.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, -15.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, -15.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(-6.0F, -8.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(-1.0F, -8.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(1.0F, -8.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.posVec(1.0F, -7.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.posVec(1.0F, -8.0F, 4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.posVec(1.0F, -8.0F, 4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(-17.5F, -25.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-120.0F, 180.0F, -45.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-180.0F, 270.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-180.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-250.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-300.0F, 580.0F, 70.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(-360.0F, 900.0F, 50.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.degreeVec(-360.0F, 900.0F, -15.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.degreeVec(-350.0F, 900.0F, -75.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.degreeVec(-350.0F, 900.0F, -75.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.degreeVec(-360.0F, 1080.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -4.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(3.0F, -4.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(10.0F, -4.0F, -5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(10.0F, -6.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(5.0F, -11.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.35F, KeyframeAnimations.posVec(1.0F, -11.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(5.0F, -11.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(1.0F, -6.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(6.0F, -8.5F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(5.0F, -7.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.65F, KeyframeAnimations.posVec(1.5F, -9.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(10.0F, -7.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.posVec(11.0F, -5.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.posVec(7.0F, -2.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.posVec(7.0F, -2.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(-32.5F, 37.5F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-32.5F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-180.0F, 270.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-180.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-250.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-330.0F, 600.0F, 15.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(-360.0F, 900.0F, 90.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.degreeVec(-360.0F, 900.0F, -75.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.degreeVec(-360.0F, 1080.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -4.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(-5.0F, -5.0F, -10.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-10.0F, -4.0F, -6.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(-5.0F, -11.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.35F, KeyframeAnimations.posVec(0.0F, -11.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(-5.0F, -11.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(-9.0F, -7.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(-13.5F, -9.0F, -2.5F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(-6.0F, -7.0F, 2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.65F, KeyframeAnimations.posVec(-3.0F, -9.0F, -2.5F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(-8.0F, -3.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.posVec(-4.0F, -9.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.posVec(-4.0F, -9.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(42.5F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(27.5F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-180.0F, 270.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-180.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-360.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-350.0F, 630.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(-360.0F, 900.0F, 30.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.degreeVec(-290.0F, 900.0F, -30.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.degreeVec(-270.0F, 900.0F, -90.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.degreeVec(-270.0F, 900.0F, -90.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.degreeVec(-360.0F, 1080.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -2.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(-4.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(4.0F, 4.0F, 4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(10.0F, 10.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(2.0F, 9.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.35F, KeyframeAnimations.posVec(0.0F, 9.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(2.0F, 9.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(8.0F, 1.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(-0.5F, -5.5F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(9.0F, -3.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.65F, KeyframeAnimations.posVec(-3.0F, -6.5F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(3.0F, 0.0F, -6.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.posVec(7.0F, 0.0F, -1.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.posVec(5.0F, 6.0F, -8.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.posVec(5.0F, 6.0F, -8.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.degreeVec(37.5F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.degreeVec(-15.0F, 180.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.degreeVec(-180.0F, 270.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.degreeVec(-180.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(-360.0F, 450.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.degreeVec(-350.0F, 630.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.degreeVec(-360.0F, 900.0F, 45.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.degreeVec(-290.0F, 900.0F, -15.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.degreeVec(-280.0F, 990.0F, -90.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.degreeVec(-280.0F, 990.0F, -90.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.degreeVec(-360.0F, 1080.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, -2.0F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.15F, KeyframeAnimations.posVec(-8.0F, -2.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2F, KeyframeAnimations.posVec(-4.0F, 4.0F, 5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.25F, KeyframeAnimations.posVec(4.0F, 9.0F, 3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.3F, KeyframeAnimations.posVec(-2.0F, 9.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.35F, KeyframeAnimations.posVec(0.0F, 9.0F, -2.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4F, KeyframeAnimations.posVec(-2.0F, 9.0F, -5.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.5F, KeyframeAnimations.posVec(4.0F, 1.0F, -4.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.55F, KeyframeAnimations.posVec(-7.5F, -5.5F, -3.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6F, KeyframeAnimations.posVec(5.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.65F, KeyframeAnimations.posVec(-2.0F, -8.0F, 3.5F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.7F, KeyframeAnimations.posVec(-5.0F, 4.0F, -7.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.75F, KeyframeAnimations.posVec(-1.0F, 0.0F, -6.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8F, KeyframeAnimations.posVec(1.0F, 0.0F, -6.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.85F, KeyframeAnimations.posVec(1.0F, 0.0F, -6.0F),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.9F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.build();
}